name: TinyPen Dev Deploy on PR to main
on:
  pull_request:
    branches: main
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge with main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: ${{ github.head_ref }}
          github_token: ${{ secrets.BRY_PAT }}
          message: Merge main into this branch to deploy to dev for testing.
  deploy:
    if: github.event.pull_request.draft == false
    needs:
      - merge-branch
    strategy:
      matrix:
        node-version:
          - 22
        machines:
          - vlcdhp02
    runs-on: ${{ matrix.machines }}
    steps:
      - uses: actions/checkout@master
      - name: Deploy the app on the server
        run: |
          if [[ ! -e /srv/node/logs/tinypen.txt ]]; then
              mkdir -p /srv/node/logs
              touch /srv/node/logs/tinypen.txt
          fi
          echo $USER
          cd /srv/node/tinyPen/
          pm2 stop tinyPen
          git stash
          git checkout main
          git pull
          git checkout $GITHUB_HEAD_REF
          git pull
          npm install
          pm2 start -i max bin/tinyPen.js
