name: TinyPen Dev Deploy on PR to main
on:
  pull_request:
    branches: main
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge with main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: ${{ github.head_ref }}
          github_token: ${{ secrets.BRY_PAT }}
          message: Merge main into this branch to deploy to dev for testing.
  deploy:
    if: github.event.pull_request.draft == false
    needs:
      - merge-branch
    strategy:
      matrix:
        machines:
          - vlcdhp02
    runs-on: ${{ matrix.machines }}
    steps:
      - uses: actions/checkout@master
      - name: Deploy the app on the server
        run: |
          if [[ ! -e /srv/node/logs/tinypen.txt ]]; then
              mkdir -p /srv/node/logs
              touch /srv/node/logs/tinypen.txt
          fi
          cd /srv/node/tinyPen/
          echo "Private Project Don't Work Without Login"
          echo "When this isn't private do the following"
          echo "pm2 stop tinyPen"
          echo "git stash"
          echo "git checkout main"
          echo "git pull"
          echo "git checkout $GITHUB_HEAD_REF"
          echo "git pull"
          echo "npm install"
          echo "pm2 start -i max bin/tinyPen.js"
